name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TP 1 math test
      id: tp-1-math-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 1
        max-score: 1
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TP-1-MATH-TEST_RESULTS: "${{steps.tp-1-math-test.outputs.result}}"
      with:
        runners: tp-1-math-test
